all: rk4_sbp4_10 rk4_sbp4_100 rk4_sbp6_10 rk4_sbp6_100
rk4_sbp4_10:
	pdflatex rk4_sbp4_10
rk4_sbp4_100:
	pdflatex rk4_sbp4_100
rk4_sbp6_10:
	pdflatex rk4_sbp6_10
rk4_sbp6_100:
	pdflatex rk4_sbp6_100

clean:
	rm -rf *.aux *.tmp *.bbl *.blg*.synctex.gz *.log *.out
